In [ ]:
### This data was collected to understand water conflicts from the Colorado River Basin.
### It includes data from 2005-2021. The author intended it to help inform water availability assessments
### to benefit the human dimension research being done on the issue.

Accessed on October 7, 2026, from https://www.sciencebase.gov/catalog/item/63acac09d34e92aad3ca1480

Holloman, D.V., Hines, M.K., and Zoanni, D.K., 2023, Coded Water Conflict and Crisis Events in the Colorado River Basin, Derived from LexisNexis search 2005-2021: U.S. Geological Survey data release, https://doi.org/10.5066/P9X6WR7J.

In [46]:
import numpy as np
import pandas as pd

In [47]:
df = pd.read_csv('data/63acac09d34e92aad3ca1480.csv')

In [3]:
df.head()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,...,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,...,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,...,18,0,0,0,0,0,0,0,0,0

In [4]:
df.shape

(268, 48)

In [5]:
df.nunique()

Event                                           268
Search Source                                     6
Newspaper                                        45
Article Title                                   267
Duplicate                                         2
Report Date                                     235
Report Year                                      18
Event Date                                       52
Event Day                                        12
Event Month                                      12
Event Year                                       21
Conflict Present                                  2
Crisis Present                                    2
Basin                                            25
HUC6                                             22
HUC2                                              7
Place                                           135
County                                            3
County FIPS                                       3
State                                            23
State FIPS                                       19
Urban or Rural                                    6
Issue Type                                       19
Event Summary                                   253
Stakeholders                                    199
Intensity Value                                  10
Comments                                        184
Related Observation Themes                       21
Article Text Search - water quality              10
Article Text Search - invasive species            2
Article Text Search - conservation               15
Article Text Search - drought                    19
Article Text Search - flood                      10
Article Text Search - ground water depletion      1
Article Text Search - depletion                   2
Article Text Search - infrastructure              9
Article Text Search - fish passage                1
Article Text Search - instream water rights       1
Article Text Search - water rights               17
Article Text Search - intergovernmental           2
Article Text Search - water transfers             2
Article Text Search - navigation                  2
Article Text Search - fish                        8
Article Text Search - invasive                    3
Article Text Search - diversion                   6
Article Text Search - water diversion             2
Article Text Search - instream                    5
Article Text Search - aquatic                     5
dtype: int64

In [6]:
df.describe()

,Event,Report Year,Event Day,Event Month,Event Year,County FIPS,Intensity Value,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
count,268.000000,265.000000,18.000000,212.000000,257.000000,8.000000,255.000000,268.000000,268.000000,268.000000,...,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
mean,134.500000,2017.449057,18.444444,6.259434,2016.591440,11170.500000,0.219608,0.671642,0.014925,2.007463,...,3.134328,0.003731,0.022388,0.007463,0.410448,0.033582,0.182836,0.011194,0.089552,0.093284
std,77.509139,4.314160,6.887518,3.679539,10.346365,15437.657326,1.995765,1.472729,0.121481,2.633681,...,3.456072,0.061085,0.148219,0.086225,1.109798,0.200166,0.734493,0.105405,0.860822,0.632064
min,1.000000,2005.000000,4.000000,1.000000,1900.000000,4027.000000,-4.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,67.750000,2015.000000,13.250000,3.000000,2015.000000,4027.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,134.500000,2019.000000,19.000000,5.000000,2019.000000,6047.000000,0.000000,0.000000,0.000000,1.000000,...,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,201.250000,2021.000000,20.000000,9.000000,2021.000000,8067.000000,1.500000,1.000000,0.000000,3.000000,...,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,268.000000,2022.000000,31.000000,12.000000,2023.000000,49055.000000,5.000000,10.000000,1.000000,15.000000,...,18.000000,1.000000,1.000000,1.000000,8.000000,2.000000,7.000000,1.000000,12.000000,9.000000

In [7]:
df.isna().sum()

Event                                             0
Search Source                                     0
Newspaper                                         0
Article Title                                     0
Duplicate                                         1
Report Date                                       1
Report Year                                       3
Event Date                                       20
Event Day                                       250
Event Month                                      56
Event Year                                       11
Conflict Present                                 16
Crisis Present                                   14
Basin                                            18
HUC6                                            158
HUC2                                             18
Place                                            14
County                                          260
County FIPS                                     260
State                                            90
State FIPS                                       90
Urban or Rural                                   14
Issue Type                                       13
Event Summary                                    12
Stakeholders                                     13
Intensity Value                                  13
Comments                                         78
Related Observation Themes                      182
Article Text Search - water quality               0
Article Text Search - invasive species            0
Article Text Search - conservation                0
Article Text Search - drought                     0
Article Text Search - flood                       0
Article Text Search - ground water depletion      0
Article Text Search - depletion                   0
Article Text Search - infrastructure              0
Article Text Search - fish passage                0
Article Text Search - instream water rights       0
Article Text Search - water rights                0
Article Text Search - intergovernmental           0
Article Text Search - water transfers             0
Article Text Search - navigation                  0
Article Text Search - fish                        0
Article Text Search - invasive                    0
Article Text Search - diversion                   0
Article Text Search - water diversion             0
Article Text Search - instream                    0
Article Text Search - aquatic                     0
dtype: int64

In [8]:
df['Issue Type'].value_counts()

Issue Type
Drought                                                                       66
Water rights more generally                                                   51
Conservation                                                                  43
Intergovernmental issues                                                      43
Infrastructure issues                                                         15
Water quality                                                                 10
Water transfers                                                                6
Instream water rights                                                          6
Flood                                                                          4
Intergovernmental issues: Water rights more generally                          2
Intergovernmental issues: Drought                                              1
Intergovernmental issues: Water transfers                                      1
Intergovernmental issues: Conservation                                         1
Conservation; Drought                                                          1
Fish passage                                                                   1
Ground water depletion                                                         1
Conservation; Water rights more generally                                      1
Drought; Water quality; Water rights more generally; Infrastructure issues     1
Conservation; Ground water depletion                                           1
Name: count, dtype: int64

In [10]:
df['Place'].value_counts()

Place
Entire Colorado River Basin                                              19
State of Arizona                                                         17
Colorado River Basin                                                     13
Great Salt Lake                                                          10
Arizona                                                                   6
                                                                         ..
Gila River Indian Reservation                                             1
Navajo Nation, Hopi Reservation                                           1
AZ, CO, NM, UT, Southern Ute Tribe, Ute Mountain tribe, Navajo Nation     1
Laughlin, AZ                                                              1
State of Arizona, State of California                                     1
Name: count, Length: 135, dtype: int64

In [16]:
df['State'].unique()

array(['CO', 'UT', nan, 'AZ', 'OH; UT', 'AZ; CO; NM; UT', 'CA', 'AZ; UT',
       'AZ; NV', 'CO; UT; WY; NM', 'AZ; CA', 'UT; AZ', 'CO; WY', 'NV; AZ',
       'CO; AZ', 'AZ; CA; CO; NV; NM; UT; WY', 'AZ; CA; NV', 'NV', 'NM',
       'UT; CO; WY', 'CA; NV; AZ', 'AZ; NM', 'WY; UT; CO', 'TX'],
      dtype=object)

In [14]:
df['Place'].unique()

array(['Durango, CO', 'Great Salt Lake',
       'Colorado River Indian Reservation',
       'Southern Ute Indian Reservation', 'State of Arizona',
       'Entire Colorado River Basin', 'All of Colorado River Basin',
       'Farmington, OH; Great Salt Lake', 'Navajo Nation; Window Rock AZ',
       'Bullhead City, AZ re: All of Colorado R. Basin', 'Phoenix, AZ',
       'Ute Tribe, Utah', 'Denver, CO; Shoshone power plant',
       'AZ, CO, NM, UT, Southern Ute Tribe, Ute Mountain tribe, Navajo Nation',
       'Colorado River Basin', 'Laughlin, AZ',
       'Colorado River Indian Reservation; Parker, AZ',
       'CA - Imperial Irrigation District', 'Flagstaff, AZ',
       'Glen Canyon Dam, Lake Powell, UT; AZ', 'Needles, CA',
       'AZ, NV, Mexico', 'CO, UT, WY, NM', 'Las Vegas, Southern CA; AZ',
       'Sacaton/Gila R. Indian Reservation', 'Boulder, CO', 'Lees Ferry',
       'AZ', 'Lake Powell (UT, AZ)', 'Glenwod Springs',
       'Multiple waterways in UT ', 'St. Michaels, AZ',
       'The Front Range, CO/WY', 'CO', 'Flagstaff, AZ; UT',
       'Las Vegas, Flagstaff, AZ', 'CO (also Phoenix/Tucson, AZ',
       'Window Rock, AZ; Navajo Nation', 'Upper basin states',
       'Greeley, CO', 'AZ, CA, CO, NV, NM, UT, WY',
       'Scottsdale, Tucson, Phoenix, AZ', 'AZ, CA, NV', 'AZ; CA',
       'Las Vegas, NV', 'Hermosa Creek',
       'Phoenix, AZ/AZ; CA; CO, NV; NM; UT, WY', 'Animas River',
       'Lake Mead', 'Long Hollow Dam', 'White River', 'Glendale',
       'Colorado River', 'Southwestern US', 'Garfield County, CO',
       'San Juan River', 'Colorado River System',
       'Navajo Nation, Hopi Reservation', 'Gila River Indian Reservation',
       'Navajo Nation', 'Green River', 'Routt County, CO',
       'Pinal County, AZ', 'Pecos River', 'Colorado State',
       'Navajo/Hopi Reservations, Lower Colorado River', 'Flaming Gorge',
       'Lake Powell', 'Lake Powell, Lake Mead, Gila River',
       'Salt Lake City', 'State of Colorado', 'Pheonix, AZ',
       'Boulder City, NV', 'Salton Sea', 'Mancos River Watershed',
       'California State', 'Washington D.C.', 'Navajo/Hopi Nations',
       'Animas River including Junction and Lightner Creeks from Bakers Bridge to the New Mexico line, La Plata RIver from Mayday to the New Mexico State line, Vellecito Creek, Pine River from Vallecito to the Southern Ute Indian Tribe reservation south of Bayfield, Florida River,',
       'The application for Utah water rights requests 55,000 acre feet of water from the Green River with two pump stations located five miles from the Colorado state line in Dagget County, Utah, on Bureau of Land Management land. The water would then run through a hydroelectric facility before being piped nearly 500 miles northeast into Wyoming and then south down the Colorado Front Range',
       nan, 'Denver, CO', 'Yuma, AZ', 'Yampa Valley, CO', 'Tuscon, AZ',
       'Central Arizona Project, AZ',
       'San Juan County, San Juan River, Navajo Nation',
       'Hoover Dam, Clark County, NV', 'Green River Community, Utah',
       'San Juan River and Lake Powell', 'Navajo Nation, AZ',
       'White Mountain Apache lands Northeast/central AZ, CRIT lands along western edge of AZ and into CA',
       'South of the Seedskadee National Wildlife Refuge',
       'State of California, Nevada, Arizona', 'Glen Canyon Dam',
       'Yuma County, AZ', 'New Mexico, Arizona',
       'Wyoming, Utah, Colorado', 'Glen Canyon Dam, Grand Canyon',
       'Animas River near Silverton, San Juan River to Lake Powell',
       'Meeker, Colorado', 'Arizona ',
       'Arizona, California, Colorado, Nevada, New Mexico, Utah, Wyoming',
       'Lower Basin', 'Navajo Generating Station, near Page, AZ',
       'La Plata County, Animas River Valley', 'Cibola, AZ',
       'Lake Mead; Bullhead City, AZ', 'Colorado River Delta',
       'Little Colorado River Basin', 'State of Utah',
       'San Juan River; Navajo Nation; New Mexico',
       'Colorado; Phoenix AZ', 'Arizona',
       'Wayne County, Utah; Green River',
       'Lower Arkansas Valley Water Conservancy District',
       'Upper Colorado River Basin', 'Green River; Utah',
       'Lower Colorado River Basin', 'Salton Sea; California',
       'Arizona; entire Colorado River Basin',
       'Rio Blanco Water Conservancy District; State of Colorado',
       'Navajo and Hopi Nations/Little Colorado River', 'Bear River',
       'Utah', 'Scottsdale, AZ', 'Colorado ', 'Grand Valley, CO',
       'Austin, TX', 'Western Slope, CO', 'Salt River', 'Green River, UT',
       'Tempe, AZ', 'Yuma, AZ ', 'Glen Canyon Dam, AZ',
       'State of Arizona, State of California'], dtype=object)

In [48]:
# Example series
s = pd.Series(['California; Nevada', 'Arizona', np.nan, 'Nevada; Utah'])
s

0    California; Nevada
1               Arizona
2                   NaN
3          Nevada; Utah
dtype: object

In [49]:
# CELL 3
# Use str accessor with additional methods to perform string operations
s.str.split(';')

0    [California,  Nevada]
1                [Arizona]
2                      NaN
3          [Nevada,  Utah]
dtype: object

In [24]:
# CELL 4
s.str.split(';').explode()

0    California
0        Nevada
1       Arizona
2           NaN
3        Nevada
3          Utah
dtype: object

In [34]:
df.loc[df['State'].notna(), "State"]

0          CO
1          CO
2          UT
5          AZ
11     OH; UT
        ...
263        CO
264        CO
265    AZ; CA
266        AZ
267        AZ
Name: State, Length: 178, dtype: object

In [50]:
# Select state column where conflict is present
states_conflict=df.loc[df["Conflict Present"] == "Y", "State"]

In [53]:
states_conflict=states_conflict.str.split(';').explode().unique()
states_conflict

AttributeError: 'numpy.ndarray' object has no attribute 'str'

In [44]:
states_conflict.str.split(" ")

AttributeError: 'numpy.ndarray' object has no attribute 'str'